# Generated by Django 4.0.5 on 2022-07-26 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.IntegerField(unique=True)),
                ('wallet_balance', models.FloatField(default=0.0)),
                ('contact_no', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_image_id', models.CharField(blank=True, max_length=200, null=True)),
                ('uplines', models.TextField(blank=True, null=True)),
                ('mother_department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_mother_department_id', to='organization_module.departmentmaster')),
                ('rm_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profile_rm_id', to=settings.AUTH_USER_MODEL)),
                ('tl_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profile_tl_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targeted_date', models.DateTimeField()),
                ('target_amount', models.FloatField(default=0.0)),
                ('achived_amount', models.FloatField(default=0.0)),
                ('completion_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('goal_initiator', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='user_goals_initiator_user_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_goals_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('credted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_department_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_department_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_department_department_id', to='organization_module.departmentmaster')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_department_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_department_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
