# Generated by Django 4.0.5 on 2022-07-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ledgertypes_ledger_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertypes',
            name='ledger_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lt_ledger_category', to='accounts.ledgercategory'),
        ),
    ]
