# Generated by Django 4.0.5 on 2022-07-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ledgertypes_ledger_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgergroup',
            name='ledger_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lg_ledger_category', to='accounts.ledgercategory'),
        ),
        migrations.AlterField(
            model_name='ledgergroup',
            name='ledger_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lg_ledger_type', to='accounts.ledgertypes'),
        ),
        migrations.AlterField(
            model_name='ledgergroup',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lg_parent_ledger_group', to='accounts.ledgergroup'),
        ),
    ]
