# Generated by Django 4.0.5 on 2022-07-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ledgergroup_ledger_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='updated_by',
        ),
    ]
