# Generated by Django 4.0.5 on 2022-07-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ledger_deleted_at_ledger_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgercategory',
            name='cr',
            field=models.CharField(choices=[('decrease', 'decrease'), ('increase', 'increase')], default='increase', max_length=10),
        ),
        migrations.AlterField(
            model_name='ledgercategory',
            name='dr',
            field=models.CharField(choices=[('decrease', 'decrease'), ('increase', 'increase')], default='decrease', max_length=10),
        ),
    ]
