# Generated by Django 4.0.5 on 2022-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_ledgercategory_cr_alter_ledgercategory_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertypes',
            name='final_account_section',
            field=models.CharField(blank=True, choices=[('trial balance', 'Trail Balance'), ('profit and loss', 'Profit & Loss'), ('balance sheet', 'Balance Sheet'), ('manufacturing', 'Manufacturing')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ledgertypes',
            name='side',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit'), ('asset', 'Asset'), ('liability', 'Liability')], default=None, max_length=50, null=True),
        ),
    ]
