# Generated by Django 4.0.5 on 2022-08-04 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_alter_ledgertypes_final_account_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgergroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ledger_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledgergroup',
            name='ledger_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lc_ledger_group', to='accounts.ledgercategory'),
        ),
        migrations.AlterField(
            model_name='ledgergroup',
            name='ledger_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lt_ledger_group', to='accounts.ledgertypes'),
        ),
        migrations.AlterField(
            model_name='ledgergroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updater_ledger_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledgertypes',
            name='ledger_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lc_Ledger_types', to='accounts.ledgercategory'),
        ),
    ]
