# Generated by Django 4.0.5 on 2022-07-11 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_address', models.TextField()),
                ('contact_no', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=200)),
                ('web_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designation_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designation_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designation_organization', to='organization_module.organizationmaster')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designation_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_organization', to='organization_module.organizationmaster')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentDesignationRelationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.IntegerField(default=0)),
                ('to_level', models.IntegerField(default=0)),
                ('chnage_type', models.CharField(choices=[('added', 'added'), ('modified', 'modified'), ('deleted', 'deleted')], default='added', max_length=10)),
                ('changed_at', models.DateTimeField(verbose_name='date published')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddrcg_changed_by', to=settings.AUTH_USER_MODEL)),
                ('departmant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddrcg_department', to='organization_module.departmentmaster')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddrcg_designation', to='organization_module.designationmaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddrcg_organization', to='organization_module.organizationmaster')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentDesignationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('assigned', 'assigned'), ('unassigned', 'unassigned')], default='assigned', max_length=10)),
                ('assigned_at', models.DateTimeField(verbose_name='date published')),
                ('unassigned_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddr_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('departmant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddr_department', to='organization_module.departmentmaster')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddr_designation', to='organization_module.designationmaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddr_organization', to='organization_module.organizationmaster')),
                ('unassigned_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ddr_unassigned_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
